import json
import collections

with open("lib/l10n/app_ar.arb", "r") as f:
    ar_data = json.load(f, object_pairs_hook=collections.OrderedDict)

translations = {
  "id": "معرف",
  "balancePlaceholder": "0.00",
  "usdBalancePlaceholder": "$0.00",
  "swapStatus": "تبادل",
  "cvvLabel": "CVV: ",
  "queryPinCode": "الاستعلام عن كلمة المرور",
  "reissuePhysicalCard": "إعادة إصدار بطاقة فعلية",
  "securityVerification": "التحقق الأمني",
  "resendCode": "إعادة إرسال",
  "query": "استعلام",
  "cardPinIs": "رمز PIN للبطاقة هو",
  "keepPinSafeTip": "يرجى الاحتفاظ به بأمان وعدم مشاركته مع الآخرين.",
  "cardBenefits": "مزايا البطاقة",
  "rates": "الأسعار",
  "monthlyFee": "رسوم شهرية",
  "monthlyLimit": "الحد الشهري",
  "fxFee": "رسوم صرف العملات",
  "transactionFee": "رسوم المعاملات",
  "crossBorderFee": "رسوم عبر الحدود",
  "failedTransactionFee": "رسوم فشل المعاملة",
  "smallTransactionFee": "رسوم المعاملات الصغيرة",
  "failedTransactionCountMonthly": "المعاملات الفاشلة (الشهر)",
  "smallTransactionCountMonthly": "المعاملات الصغيرة (الشهر)",
  "instructions": "تعليمات:",
  "failedTransactionFeeDesc": "1. رسوم فشل المعاملة: بدءًا من 18 نوفمبر 2025، سيتم فرض رسوم قدرها 0.4 دولار على كل معاملة فاشلة.",
  "smallTransactionFeeDesc": "2. رسوم المعاملات الصغيرة: بدءًا من 1 أبريل 2024، سيتم فرض رسوم قدرها 0.15 دولار على المعاملات التي تقل عن 10 دولارات.",
  "mailingProgress": "تقدم البريد",
  "mailingProgressTitle": "تقدم البريد",
  "upgradeApplication": "ترقية التطبيق",
  "applicationTime": "وقت التطبيق",
  "cardProduction": "إنتاج البطاقة",
  "cardShipped": "تم شحن البطاقة",
  "shippedTime": "وقت الشحن",
  "courierTracking": "تتبع البريد",
  "activateCardStep": "تفعيل البطاقة",
  "activateCardTip": "يرجى التفعيل بعد استلام البطاقة!",
  "cardReceived": "تم استلام البطاقة",
  "reminder": "تذكير",
  "activationConfirmTip": "يرجى التأكد من استلام البطاقة الفعلية قبل التفعيل!",
  "notReceivedActivateLater": "لم يتم الاستلام، قم بالتفعيل لاحقًا",
  "receivedActivateNow": "تم الاستلام، قم بالتفعيل الآن",
  "physicalCardPreparing": "يتم تجهيز البطاقة الفعلية...",
  "applyPhysicalCardSuccessTitle": "لقد تقدمت بطلب للحصول على بطاقة فعلية بنجاح!",
  "youCanIn": "يمكنك عرض ",
  "cardTab": "[البطاقة]",
  "screenView": " شاشة للحصول على ",
  "mailingProgressTabDesc": "[تقدم البريد]\n",
  "willSendCardSoonTip": "سنرسل بطاقتك في أقرب وقت ممكن، يرجى ترقبها!\n",
  "pleaseActivateAfterReceiving": "يرجى تفعيله بعد الاستلام.",
  "backButton": "رجوع",
  "kycVerificationReadyMsg": "لقد أكملت دفع رسوم البطاقة، يمكنك الآن متابعة تحقق KYC.",
  "selectACoupon": "حدد قسيمة",
  "minFeeLabel": "الحد الأدنى للرسوم: ",
  "maxDiscountLabel": "أقصى خصم: ",
  "validUntilLabel": "صالح حتى: ",
  "completedStatus": "مكتمل",
  "failedToGetCardInfo": "فشل في تحميل معلومات البطاقة: ",
  "failedToLoadCardDetails": "فشل في تحميل تفاصيل البطاقة",
  "failedToLoadCardDetailsRefresh": "فشل في تحميل تفاصيل البطاقة. يرجى سحب الشاشة للأسفل للتحديث.",
  "chooseVerificationMethod": "اختر طريقة التحقق",
  "copied": "تم النسخ",
  "cardReplaceRenew": "استبدال/تجديد البطاقة",
  "rewardNews": "أخبار المكافآت",
  "cardHolderLabelText": "الاسم",
  "expiryDateLabelText": "تاريخ الانتهاء",
  "failedToGetProfile": "فشل في الحصول على الملف الشخصي",
  "failedToInitializeDiditToken": "فشل في تهيئة رمز Didit",
  "credit": "ائتمان",
  "debit": "مدين",
  "registrationSuccessful": "تم التسجيل بنجاح! يرجى تسجيل الدخول باستخدام بريدك الإلكتروني وكلمة المرور.",
  "kycVerification": "التحقق من KYC",
  "level1Verification": "التحقق من المستوى 1",
  "featuresAndPermissions": "الميزات والأذونات",
  "completeAuthentication": "إكمال المصادقة",
  "applyCardLabel": "طلب بطاقة",
  "documentVerification": "التحقق من الوثيقة",
  "faceRecognition": "التعرف على الوجه",
  "noKycData": "لا تتوفر بيانات KYC",
  "passed": "تم الاجتياز",
  "pending": "قيد الانتظار",
  "newPhoneCannotBeEmpty": "لا يمكن أن يكون رقم الهاتف الجديد فارغًا",
  "unexpectedResponse": "استجابة غير متوقعة",
  "emailPhoneOtpRequired": "لا يمكن أن يكون البريد الإلكتروني ورقم الهاتف الجديد ورمز OTP للهاتف فارغًا",
  "newPhoneEmailOtpRequired": "لا يمكن أن يكون رقم الهاتف الجديد ورمز OTP للبريد الإلكتروني فارغًا",
  "amountGreaterThanZero": "يجب أن يكون المبلغ أكبر من 0",
  "failedToCreateQuote": "فشل إنشاء الاقتباس: خطأ في تنسيق البيانات",
  "chatHowToStart": "كيف تبدأ محادثة",
  "chatStep1": "انقر على زر المحادثة الأزرق في الزاوية السفلية اليمنى",
  "chatStep2": "اكتب سؤالك أو استفسارك",
  "chatStep3": "فريق الدعم الخاص بنا سيرد عليك قريبا",
  "chatFaqTitle": "الأسئلة الشائعة",
  "chatFaqQ1": "ما هي ساعات الدعم الخاصة بكم؟",
  "chatFaqA1": "فريقنا متاح 24/7 لمساعدتك.",
  "chatFaqQ2": "ما مدى سرعة الرد؟",
  "chatFaqA2": "يتم الرد على معظم الاستفسارات في غضون 2-5 دقائق.",
  "chatFaqQ3": "هل يمكنني إرفاق ملفات؟",
  "chatFaqA3": "نعم، يمكنك إرسال الصور والمستندات من خلال المحادثة.",
  "chatFaqQ4": "هل محادثتي آمنة؟",
  "chatFaqA4": "نعم، جميع المحادثات مشفرة وسرية.",
  "chatOtherContactMethods": "طرق الاتصال الأخرى",
  "chatEmailSupport": "البريد الإلكتروني: support@comecomepay.com",
  "chatResponseTime": "وقت الاستجابة: خلال 24 ساعة",
  "chatClickHint": "انقر هنا لبدء المحادثة!",
  "chatAgentOnline": "الوكيل متصل",
  "chatHelpSubtitle": "نحن هنا لمساعدتك 24/7",
  "chatInitConnection": "جاري تهيئة الاتصال...",
  "chatLoadingService": "تحميل خدمة المحادثة...",
  "chatSettingSecure": "إعداد القناة الآمنة...",
  "chatAlmostReady": "قريباً...",
  "chatConnectingTitle": "الاتصال بخدمة العملاء",
  "chatSettingSession": "إعداد جلسة المحادثة الخاصة بك...",
  "threeDsPaymentAuth": "تصريح الدفع",
  "threeDsPendingConfirm": "لديك معاملة معلقة للتأكيد",
  "threeDsConfirmTip": "يرجى التحقق بعناية من تفاصيل المعاملة أدناه للتأكد من أنها عملية شراء خاصة بك. إذا لم يتم التصريح خلال الوقت المحدد، فسيتم إلغاء المعاملة.",
  "threeDsAmount": "مبلغ المعاملة",
  "threeDsMerchant": "معلومات التاجر",
  "threeDsTxId": "رقم المعاملة",
  "threeDsCreatedAt": "وقت الإنشاء",
  "threeDsApprove": "موافقة",
  "threeDsReject": "رفض",
  "threeDsAuthDetails": "تفاصيل التفويض",
  "threeDsAuthTime": "وقت التفويض",
  "threeDsTxTime": "وقت المعاملة",
  "threeDsPending": "قيد الانتظار",
  "threeDsApprovedSuccess": "✅ تمت الموافقة على المعاملة عند: {merchant}",
  "threeDsRejectedSuccess": "❌ تم رفض المعاملة",
  "threeDsApproveFailed": "فشلت الموافقة: {error}",
  "threeDsRejectFailed": "فشل الرفض: {error}"
}

for k, v in translations.items():
    if k in ar_data:
        ar_data[k] = v

with open("lib/l10n/app_ar.arb", "w") as f:
    json.dump(ar_data, f, indent=2, ensure_ascii=False)

print("Translated successfully.")
