// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoSD7_xF5X1K3Ai4RUuuHqk17V60p6SQo',
    appId: '1:1025601932935:web:194c65436a41593de17222',
    messagingSenderId: '1025601932935',
    projectId: 'comepay-b9607',
    authDomain: 'comepay-b9607.firebaseapp.com',
    storageBucket: 'comepay-b9607.firebasestorage.app',
    measurementId: 'G-Z8X4YGMNT0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk9fLNKMVhV0tJEdNZRCU2dqRBpb_JFfk',
    appId: '1:1025601932935:android:6e05be85405ea50ce17222',
    messagingSenderId: '1025601932935',
    projectId: 'comepay-b9607',
    storageBucket: 'comepay-b9607.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFUbCTLyiWdMmebIRf17VlOZE6WQp40zY',
    appId: '1:1025601932935:ios:7b4c14626b419290e17222',
    messagingSenderId: '1025601932935',
    projectId: 'comepay-b9607',
    storageBucket: 'comepay-b9607.firebasestorage.app',
    iosBundleId: 'com.example.comecomepay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFUbCTLyiWdMmebIRf17VlOZE6WQp40zY',
    appId: '1:1025601932935:ios:7b4c14626b419290e17222',
    messagingSenderId: '1025601932935',
    projectId: 'comepay-b9607',
    storageBucket: 'comepay-b9607.firebasestorage.app',
    iosBundleId: 'com.example.comecomepay',
  );
}
